# .github/workflows/docs.yml
name: Docs

on:
  pull_request:
    branches: [master]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install with docs extras
        run: |
          poetry install --with docs --no-interaction
      - name: Build docs
        run: |
          poetry run sphinx-build -b html docs/source docs/_build/html
